### ISSUE TITLE
More and better tests with Cypress.

### ISSUE THREAD

**Issue by ehowey** [ehowey/gatsby-theme-catalyst#379]
Right now cypress is under utilized - more tests are needed. Currently there is just a "smoke" test and an awesome accessibility audit. More would be better though, especially as the project grows and gets more complex.

**Comment by ehowey** [comment]
Should also automate these with a github action...

**Comment by duncanjbain** [comment]
Hi @ehowey, I’m pretty (see also: very) new to web development and React/Gatsby in general, but I’m looking at learning more on testing.

I could spend a bit of time looking into this if you’re not already on the case.

Great theme by the way! I’m going to use Gatsby for my personal blog/site which will be used to track my progress and to “learn in public”, I would say the end goal is to probably create my own Gatsby theme but until I do so this one will be perfect 😃

**Comment by ehowey** [comment]
That would be great! I am new to testing and cypress too. So don’t worry we can learn together. I found the learn with Jason episode about testing really helpful to get an overview and get started with it.

Let me know if you have questions and thanks for the feedback!

**Comment by duncanjbain** [comment]
I thought it might be a good idea to get some unit testing implemented prior to the end to end testing with Cypress so I've made a start on unit testing with the core theme first.

#393

**Comment by ehowey** [comment]
If anyone is following along, we had a bit of a back and forth discussion in the PR. Next step is to look at GH actions, looking for the path of least resistance and maximum value in testing. Potentially favoring just Cypress over Jest+Cypress but that is TBD. Duncan did some awesome work on the PR!

**Comment by ehowey** [comment]
So I have the testing setup to run automatically now with a GH Action. Now I need to actually add some more tests in but this is a step in the right direction.
