### ISSUE TITLE
Process for adding additional plugins to gatsby-plugin-mdx remark plugins option

### ISSUE THREAD

**Issue by ehowey** [ehowey/gatsby-theme-catalyst#525]
**Issue**

As per an email conversation with someone using this theme - it is tricky to add additional remark plugins to the theme via a starter - the remark plugins are specified in `gatsby-theme-catalyst-core` and overriding those in the starter introduces some friction points.

**Potential solution**

I think a potential solution is to use theme options as feature flags to conditionally include/exlcude the plugins in `gatsby-config.js`.  I haven't done this yet in the themes but I do know it is possible.  This would allow a greater degree of customization when it comes to remark plugins but keep a basic set of plugins as a base. I just need to make sure this wouldn't have a drastic effect on site performance.

**Comment by ehowey** [comment]
Partially addressed by #527 

Added some additional remark plugins - these only added or improved the current functioning. See PR for details.

**Comment by johngrasty** [comment]
Hey Eric,

Thanks for the work on this. Due to the craziness of life now, I had not responded. Sorry about that. This certainly is a tricky problem, I discovered!

**Comment by ehowey** [comment]
I did add `gatsby-remark-relative-paths` - so hopefully that would solve this problem for you? The other plugin you mentioned in your email hadn't been updated in a while which made me a bit nervous to include it.

Let me know if it is working better for you now!

**Comment by ehowey** [comment]
@johngrasty #781 shows a pattern I can use for this in the future. I conditionally added a remark plugin behind a feature flag, so setting `useKatex` to true enables `gatsby-remark-katex` for a site.

Any other remark plugins you would need implemented this way?
