### ISSUE TITLE
add RSS feed of blog content

### ISSUE THREAD

**Issue by ahdinosaur** [ehowey/gatsby-theme-catalyst#604]
**Is your feature request related to a problem? Please describe.**
[RSS](https://en.wikipedia.org/wiki/RSS) is a standardized way for users to listen to updates on your site. while declining in popularity, i think it signals support for accessibility that some users would appreciate. :star2: 

**Describe the solution you'd like**
i experimented with adding this to my site using `gatsby-plugin-feed`: 

- rss feed: https://villagekit.com/rss.xml
- code: https://github.com/villagekit/villagekit.com/blob/889a0dec000ace1b96cda737ed51d2594381e2ac/gatsby-config.js#L116-L180

```javascript
    {
      resolve: `gatsby-plugin-feed`,
      options: {
        query: `
          {
            site {
              siteMetadata {
                title
                description
                siteUrl
              }
            }
          }
        `,
        feeds: [
          {
            output: `/rss.xml`,
            title: `Village Kit RSS Feed`,
            query: `
              {
                allCatalystPost(
                  sort: { fields: [date, title], order: DESC }
                  limit: 1000
                  filter: { draft: { eq: false } }
                ) {
                  nodes {
                    id
                    slug
                    title
                    author
                    excerpt
                    date(formatString: "ddd, DD MMM YYYY HH:mm:ss ZZ")
                    featuredImage {
                      childImageSharp {
                        resized:resize(width: 1024) {
                          src
                        }
                      }
                    }
                  }
                }
              }
            `,
            serialize: ({
              query: {
                site: {
                  siteMetadata: { siteUrl },
                },
                allCatalystPost,
              },
            }) => {
              return allCatalystPost.nodes.map((node) => ({
                guid: `${siteUrl}/id/${node.id}`,
                link: `${siteUrl}${node.slug}`,
                title: node.title,
                author: node.author,
                description: node.excerpt,
                pubDate: node.date,
                image: `${siteUrl}${node.featuredImage.childImageSharp.resized.src}`,
              }))
            },
          },
        ],
      },
    },
```

**Describe alternatives you've considered**
if this isn't a priority, that's okay too, i just thought i'd share. :smiley_cat: 

**Additional context**
thanks again for `gatsby-theme-catalyst`! :tada:

**Comment by ehowey** [comment]
@ahdinosaur This looks great - it has been on my radar for a while just not a priority with limited time. If you wanted to adapt this into a PR for `catalyst-blog` you could do that.  I could also do it myself - I am plugging away at trying to get a more general blog theme released to demonstrate how people can use variants and component shadowing for a totally custom look.  Let me know if you would like to do it or I can.  I appreciate the feedback and encouragement it means a lot!

**Comment by ehowey** [comment]
See: https://github.com/ehowey/gatsby-theme-catalyst/pull/644

**Comment by ehowey** [comment]
@ahdinosaur Merged in this feature. Thank-you so much for the head start and help with it! I had to change a couple of things and there is now a `rssTitle` option in the blog theme which lets you set the title of the RSS feed dynamically!  Will be released in a few moments once all my tests pass.
