### ISSUE TITLE
links blend too much(in dark mode)?

### ISSUE THREAD

**Issue by tomByrer** [ehowey/gatsby-theme-catalyst#621]
**Describe the bug**
Link contrast is too poor to read well.

![image](https://user-images.githubusercontent.com/1308419/82618404-98da5080-9b98-11ea-8f18-30bb74f7c53c.png)

**Desktop (please complete the following information):**
Win 10, Firefox nightly, I think I have OS dark mode on.

I'm not sure of the best solution.  Maybe a lighter blue with a thin underline?

ty

**Comment by ehowey** [comment]
Fixed - damn lock files in monorepos - there is an issue where the main lock file is updated in the workspace but lock files buried deeper don't get updated.  I have to do some digging to see what is causing this and find a longer term fix than manually rebuilding the lock file and forcing netlify to clear the cache.

Thanks for the heads up!  You may have to refresh/go on a private tab to see changes.
