### ISSUE TITLE
Component Shadowing

### ISSUE THREAD

**Issue by Rolando-Barbella** [ehowey/gatsby-theme-catalyst#633]
Hi,

Thanks for creating this, I am playing with the **gatsby-theme-catalyst-hydrogen** theme, according to the docs, you can "radically change the whole visual design" of the template, but I don't see any component that I can view or modify, how can I, for example, remove or change the "Published work" button?

Thanks

**Comment by ehowey** [comment]
Hello @Rolando-Barbella!

Thanks for the question - I assume you are talking about the button on the home page?

This could be removed by shadowing the file `src -> components -> home-page -> home-work.js`.

In the starter the theme files are "hidden" in the node_modules folder but can all be easily shadowed using component shadowing.  You can read about here: https://www.gatsbyjs.org/docs/themes/shadowing/

The other option if you wanted to change the visual design of the button would be to shadow the button component itself. This is accessed at `src -> components -> button-secondary.js`.

A final option to customize the theme is to use variants form Theme-UI to change aspects of the visual design, like link colors, etc.

https://www.gatsbycatalyst.com/docs/theme-ui

I hope that helps.  If you give me a bit more detail on what you are trying to do I can probably be more specific in the details of what to do.  For an example of where this is all done in a live site you can checkout the shadowing in https://github.com/ehowey/briannasharpe which is a customized version of the theme.

**Comment by Rolando-Barbella** [comment]
Hi @ehowey, thanks very much for the answer, I took as reference your **gatsby-theme-catalyst-hydrogen/components/**  folder from  https://github.com/ehowey/briannasharpe and it works now! however, some of the styles from the _home-hero_ component "went lost", you have any idea why? I haven't modified anything else.

I new to gatsby, thanks again for the help :)

![Screen Shot 2020-05-26 at 13 33 39](https://user-images.githubusercontent.com/6339809/82876090-dd2d6e00-9f55-11ea-8f5f-8087b3e7f4e9.png)

**Comment by ehowey** [comment]
Can you give me a link to the repo so I can look at the code? It looks like probably you removed something you shouldn't have? But hard to tell without looking at the component and how you shadowed it.

**Comment by Rolando-Barbella** [comment]
Yes, sure, this what I have so far

https://github.com/Rolando-Barbella/new-blog

thanks so much :)

**Comment by ehowey** [comment]
@Rolando-Barbella Sorry for the delay.  The styles look like they are still there from what I can tell.

To be frank if you are wanting this for a blog this probably isn't the right theme.  It is for a freelance writer - like one who is working professionally in news/journalism.  You could try `gatsby-theme-catalyst-helium` but the content there is authored in MDX.  If you are wanting a plain blog with SANITYI would try this:

https://www.sanity.io/create?template=sanity-io/sanity-template-gatsby-blog

**Comment by Rolando-Barbella** [comment]
@ehowey No worries, thanks for the help, the styles do look a bit different if you compare to the original design shown here https://gatsby-starter-catalyst-hydrogen.netlify.app/ the image is not taken the full height, the font family changes as well, but I will sort out, it's fine :)

Thanks for blog recommendation, it makes more sense indeed

**Comment by ehowey** [comment]
Good luck!  Let me know when it is up! Love to see what you have made!
