### ISSUE TITLE
gatsby-starter-catalyst broken

### ISSUE THREAD

**Issue by Lane** [ehowey/gatsby-theme-catalyst#943]
**Describe the bug**
Trying to create a new gatsby project using `gatsby-starter-catalyst`, but after creating and running `gatsby develop` I receive errors.

**To Reproduce**
Following instructions from the README:
1. `gatsby new catalyst https://github.com/ehowey/gatsby-starter-catalyst`
2. `cd catalyst`
3. `gatsby develop`

**Expected behavior**
The site should build and serve.

**Screenshots**

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/21034/94760362-8c90ac00-035f-11eb-8616-445862a19987.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Node: 12.18.4

**Comment by ehowey** [comment]
Hi Lane - I just tried this myself and couldn't reproduce the bug.  Can you try `rm -rf node_modules yarn.lock` and then `yarn install`.  It almost makes me suspect a corrupted node_modules folder somehow.  When these kind of weird bugs show up that is always my first step. 

If that doesn't work we will have to dig deeper...I am actively building projects using it and not running into this bug right now it makes me think it is something else...

What version of Gatsby are you on/running?

**Comment by ehowey** [comment]
Also - I checked your profile and see you are a fellow Albertan! We could just chat on the phone about it even!

**Comment by Lane** [comment]
Small world, always good to run across a fellow Albertan in the digital space! 😄 

I tried `rm -rf node_modules package-lock.json` and then `npm install` as I tend to use npm, but ended up getting the same error.  Then I gave `rm -rf node_modules` and `yarn install` a shot and everything seems to work fine. 🤷 

Appreciate the help, catalyst looks great, looking forward to using it!

**Comment by ehowey** [comment]
Let me know if you have questions or get stuck!
